apiVersion: 1
datasources:
  - uid: local-pyroscope
    type: grafana-pyroscope-datasource
    name: Pyroscope
    url: http://pyroscope:4040
    access: proxy
    editable: true
    jsonData:
      minStep: "15s"
      backendType: "pyroscope"
